### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by monty97** [9d8dev/next-wp#8] opened 2024-06-27 13:24 UTC
![image](https://github.com/9d8dev/next-wp/assets/25929302/5a274914-f9da-4bac-8055-125401b019ff)

**Comment by brijr** [comment] 2024-06-27 20:28
@monty97 can you give a bit more context?

**Comment by monty97** [comment] 2024-06-28 15:01
![image](https://github.com/9d8dev/next-wp/assets/25929302/c76fbabc-4c89-4810-adac-8eadd96e881f)

when clone this repo and add .env.local and start the dev server and in website head to posts section this error will appear my wp rest API data is also in proper json format other things like tags, categories, pages are working fine

**Comment by youngbloodcyb** [comment] 2024-06-29 05:33
My initial feeling is that there is something up with the structure of the JSON output that we're not accounting for in the code. Do you have any custom attributes on posts or is it all default? 

It's hard to debug without seeing the exact JSON response from the REST API. Can you provide an example of the output? I bet a minor change in some of the server functions might be the fix

**Comment by monty97** [comment] 2024-06-29 05:42
https://flizzyy.com/wp-json/wp/v2/users check this

**Comment by youngbloodcyb** [comment] 2024-06-30 05:00
sweet thank you I'll dive into this

**Comment by youngbloodcyb** [comment] 2024-07-02 00:53
@monty97 are you still getting the same error? I'm unable to reproduce it. 

This is the `.env.local` I am using:

```
WORDPRESS_URL="https://flizzyy.com/"
WORDPRESS_HOSTNAME="flizzyy.com"
```

Everything is working correctly. 

I also used yarn to try to replicate your dev environment.

**Comment by youngbloodcyb** [comment] 2024-07-02 16:41
Marking as closed, feel free to comment again if it's giving troubles

**Closed by youngbloodcyb** 2024-07-02 16:41 UTC
Labels: bug
